version: "3.9"

name: imtiaz_mart_gpt

services:
  api:
    build:
      context: ./login_or_signup
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000  
    environment:
      DATABASE_URL: "postgresql://neondb_owner:kz7jBqK5RQNM@ep-flat-snow-a59h4e3g.us-east-2.aws.neon.tech/neondb?sslmode=require"